import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/landingPage/header/header'
import Main from '../components/landingPage/main/main'

const inter = Inter({ subsets: ['latin'] })

const Landing = () => {
  return (
    <>
      <Head>
        <title>متغیر | بنر ساز آنلاین</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Main />
      <footer></footer>
    </>
  )
}

export default Landing;