import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Logo from '../public/moteghayer-logo.svg'
import laptopImg from '../assets/images/laptop.svg'
import downArrowIco from '../assets/icons/down-arrow.svg'
import targetImg from '../assets/images/target.svg'
import comeDownImg from '../assets/images/come-down.png'
import GetStartedBtn from '../components/landingPage/getStartedBtn'

console.log(comeDownImg.src);
const inter = Inter({ subsets: ['latin'] })

const Landing = () => {
  return (
    <>
      <Head>
        <title>متغیر | بنر ساز آنلاین</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='w-full relative f-col-center bg-black-800' style={{height: '83vh'}}>
        <div className='w-4/5 z-10'>
          <nav className='f-between w-full my-8'>
            <div className='f-between'>
              <Image 
                src={Logo}
                alt='لوگو متغیر'
                width={75}
                height={0}
              />

              <div className='mr-2 mt-1 text-black-600'>
                <h3 className='text-2xl font-bold -mb-2.5'>متغیر</h3>
                <span className='opacity-70 text-black-500'>بنر ساز آنلاین</span>
              </div>
            </div>

            <div>
              <Link className='opacity-70' href='/login'>ورود</Link>
              <Link className='mx-7 opacity-70' href='/contact-us'>ارتباط با ما</Link>
              <GetStartedBtn />
            </div>
          </nav>

          <div className='f-between w-full' style={{height: '70vh'}}>
            <div className='w-1/3'>
              <h2 
                className='w-full text-orange-800 text-4xl font-bold picoopicFont'
                style={{lineHeight: '2.8rem'}}
              >
                از تغییر نترسید زیرا تغییر قانون زندگی و موفقیت است
              </h2>
              <p className='mb-5 mt-1.5 opacity-50'>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.</p>
              <GetStartedBtn />
            </div>

            <div className='w-3/4 f-center -ml-24'>
              <Image 
                src={laptopImg}
                alt='لوگو متغیر'
                width={650}
                height={0}
              />
            </div>
          </div>
        </div>

        <div 
          style={{background: `url(${comeDownImg.src})`, backgroundSize: '100% 100%'}} 
          className='w-full h-16 block absolute right-0 -bottom-16 z-0'
        >
          <Image 
            className='animate-bounce cursor-pointer mx-auto mt-16'
            src={downArrowIco}
            alt='لوگو متغیر'
            width={30}
            height={0}
          />
        </div>
      </header>

      <main className=''>
        <section>
          
        </section>
        <section>
          <Image
            src={targetImg}
            alt='لوگو متغیر'
            width={650}
            height={0}
          />
        </section>
      </main>
      <footer></footer>
    </>
  )
}

export default Landing;